# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

os: linux
dist: xenial

language: python

python:
    - "3.6"

services:
  - postgresql
  - redis-server

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433

env:
    matrix:
        # - TESTENV=docs
        - TESTENV=code
        # - TESTENV=pylint

# command to install dependencies
install:
    - postgres --version
    - pip install .
    - pip install -r requirements.txt
    - if [[ "$TESTENV" == "docs" ]]; then pip install sphinx;fi
    - if [[ "$TESTENV" == "pylint" ]]; then pip install pylint;fi

# command to run tests
script:
    - if [[ "$TESTENV" == "code" ]]; then coverage run --source=. manage.py test --settings=gifts_rest.settings.test; fi
    - if [[ "$TESTENV" == "docs" ]]; then ./scripts/travis/docs_harness.sh; fi
    - if [[ "$TESTENV" == "pylint" ]]; then ./scripts/travis/pylint_harness.sh; fi

after_success:
    coveralls